name: Auto-publish and auto-release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - prod
jobs:
  build:
    name: Build
    outputs:
      tag: ${{ env.tag }}
      version: ${{ env.version }}
      version_changed: ${{ steps.check.outputs.changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          diff-search: true

      - run: |
          echo "version=${{ steps.check.outputs.version }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      - name: Build for latest tag
        if: contains(github.ref, 'prod') || github.event_name == 'workflow_dispatch'
        run: |
          echo "tag=latest" >> $GITHUB_ENV
          npx tsc index.ts
          cp index.js index-latest.js

      - name: Build for tagged version
        if: steps.check.outputs.changed == 'true' && contains(github.ref, 'main')
        run: |
          echo "tag=${{ steps.check.outputs.version }}" >> $GITHUB_ENV
          npx tsc index.ts
          cp index.js index-${{ steps.check.outputs.version }}.js

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-file 
          path: index-*.js
          retention-days: 3
          if-no-files-found: error
